import math, json, random
from Game import *
from Constant import *
from Map import *
from Tile import *
from Location import *
from Rect import *
from Object import *
from Fighter import *
from BasicMonster import *